services:
  port-notification-app:
    build: .
    container_name: port-notification-app
    environment:
    - CONFIG_REDIS_HASH_KEY=notification-service:production  # ✅ Redis wali exact key
    - REDIS_URL=${REDIS_URL}
    - REDIS_ENV=notification-service
    networks:
      - portfolio-network
    restart: always

networks:
  portfolio-network:
    external: true