services:
  port-notification-app:
    build: .
    container_name: port-notification-app
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - KAFKA_BROKERS=port-kafka:29098
      - KAFKA_TOPIC=backend-topic,payment_success
      - WHATSAPP_ENABLED=true
    networks:
      - portfolio-network
    restart: always

networks:
  portfolio-network:
    external: true
